#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ATTRACTIONS = ROOT / 'redesign-site' / 'content' / 'attractions'


def patch(item_id, values):
    path = ATTRACTIONS / f'{item_id}.json'
    data = json.loads(path.read_text(encoding='utf-8'))
    data.update(values)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')


translations = {
    'attraction_1769868164287': {
        'title_es': 'MALINAS EN BARCO',
        'title_de': 'MECHELEN VOM WASSER',
        'description_es': '¿Cansado de caminar pero todavía con ganas de descubrir el centro de Malinas? Tenemos una propuesta perfecta: un paseo en barco por el Dijle.\n\nSiéntate, relájate y deja pasar el tiempo mientras recorres el Binnendijle desde el agua. Rederij Malinska ofrece diferentes recorridos por los canales, además de cruceros gastronómicos y paseos nocturnos.\n\n- Del 7 al 29 de marzo: todos los sábados\n- Del 4 de abril al 8 de noviembre: todos los días\n- Del 14 al 21 de noviembre: todos los sábados',
        'description_de': 'Sind Ihre Füße langsam müde, Sie möchten das Zentrum von Mechelen aber trotzdem weiter entdecken? Dann haben wir einen passenden Tipp: eine Bootsfahrt auf der Dijle.\n\nLehnen Sie sich zurück, entspannen Sie sich und lassen Sie die Stadt bei einer schönen Fahrt auf der Binnendijle an sich vorbeiziehen. Rederij Malinska bietet verschiedene Grachtenfahrten sowie kulinarische und abendliche Bootstouren an.\n\n- 7. bis 29. März: jeden Samstag\n- 4. April bis 8. November: täglich\n- 14. bis 21. November: jeden Samstag'
    },
    'attraction_1769868261502': {
        'title_es': 'CERVECERÍA HET ANKER',
        'title_de': 'BRAUEREI HET ANKER',
        'description_es': 'La cervecería Het Anker es conocida en todo el mundo por su cerveza Gouden Carolus. Fundada en 1471, es una de las cervecerías más antiguas de Bélgica. Las tres calderas de cobre de la sala de cocción datan de después de la Segunda Guerra Mundial. En la década de 1990, Charles Leclef, quinta generación de la familia, restauró los edificios históricos y modernizó las instalaciones de refrigeración, fermentación y maduración.\n\nExisten varias versiones de Gouden Carolus. La más conocida es, sin duda, Gouden Carolus Classic. Esta cerveza especial ganó por tercera vez una medalla de oro en los World Beer Awards en 2012. El jurado destacó su aroma rico, con notas de melaza, toffee y pera, su carácter potente pero suave, su cuerpo generoso, los sabores afrutados y un final largo y cálido.\n\nEn algunos cafés, y naturalmente en la propia brasserie de Het Anker, las diferentes cervezas se sirven en vasos de degustación. La cervecería puede visitarse, pero el número de visitantes es limitado. Se recomienda reservar para visitas individuales y la reserva es obligatoria para grupos.',
        'description_de': 'Die Brauerei Het Anker ist weltweit für ihr Gouden-Carolus-Bier bekannt. Sie wurde 1471 gegründet und gehört damit zu den ältesten Brauereien Belgiens. Die drei kupfernen Braukessel im Sudhaus stammen aus der Zeit nach dem Zweiten Weltkrieg. In den 1990er-Jahren restaurierte Charles Leclef, die fünfte Generation der Familie, die historischen Gebäude und modernisierte die Kühl-, Gär- und Lageranlagen.\n\nGouden Carolus gibt es in mehreren Varianten. Die bekannteste ist zweifellos Gouden Carolus Classic. Dieses Spezialbier gewann 2012 zum dritten Mal eine Goldmedaille bei den World Beer Awards. Die Jury hob das volle, reiche Aroma mit Noten von Melasse, Toffee und Birne, den kraftvollen und zugleich weichen Charakter, den üppigen Körper, fruchtige Aromen und einen langen, wärmenden Abgang hervor.\n\nIn einigen Cafés und natürlich auch in der Brasserie von Het Anker werden die verschiedenen Biere in Degustationsgläsern serviert. Die Brauerei kann besichtigt werden, die Besucherzahl ist jedoch begrenzt. Für Einzelbesucher wird eine Reservierung empfohlen, für Gruppen ist sie erforderlich.'
    },
    'attraction_1769868330014': {
        'title_es': 'PALACIO DE MARGARITA DE AUSTRIA',
        'title_de': 'PALAIS MARGARETE VON ÖSTERREICH',
        'description_es': 'Margarita de Austria fue gobernadora de los Países Bajos de los Habsburgo entre 1507 y 1530. Su residencia fue el Hof van Savoye, o Palacio de Saboya, considerado el primer edificio renacentista de los Países Bajos. Desde aquí se difundió el Renacimiento por la región. Merecen especial atención su magnífica fachada renacentista y el encantador jardín. Entre 1616 y 1796 el palacio albergó el Gran Consejo, el máximo tribunal de los Países Bajos meridionales. En la fachada todavía pueden verse el escudo de Margarita, el de Carlos V y una representación de la Justicia.\n\nLa vida de Margarita fue agitada desde muy joven. Fue prometida en matrimonio nada menos que tres veces. El príncipe heredero francés la devolvió cuando tenía once años porque encontró una alianza matrimonial más conveniente. Después, el heredero español Don Juan murió pocos meses después de su boda. Y Filiberto de Saboya, el gran amor de su vida, falleció tras tres años de matrimonio. Margarita, con solo veinticuatro años, vistió de viuda desde entonces y se negó a volver a casarse.\n\nEn 1507 fue nombrada gobernadora de los Países Bajos y se instaló en Malinas. Se responsabilizó de la educación del futuro emperador Carlos y de sus hermanas. Según sus contemporáneos, gobernó con tacto y visión de futuro. Uno de sus mayores éxitos fue la Paz de las Damas de Cambrai de 1529, lograda tras duras negociaciones con Luisa de Saboya, madre del rey de Francia y hermana del difunto Filiberto.\n\nMientras tanto, las artes y las ciencias florecieron en la corte de Margarita. Artistas y pensadores destacados se alojaron en el palacio y la música polifónica fue una de las grandes pasiones de la gobernadora. Su gradual original se conserva en los archivos de la ciudad de Malinas y figura entre las obras destacadas del patrimonio flamenco.\n\nSegún la información incluida actualmente en el sitio, el jardín del Palacio de Margarita de Austria abre entre semana de 07:30 a 16:15 y los sábados de 08:30 a 15:30; permanece cerrado los domingos. Durante los meses de verano se indica una apertura hasta las 18:00 los sábados.',
        'description_de': 'Margarete von Österreich war von 1507 bis 1530 Statthalterin der habsburgischen Niederlande. Ihr Wohnpalast war der Hof van Savoye, der als erstes Renaissancegebäude der Niederlande gilt. Von hier aus verbreitete sich die Renaissance in der Region. Besonders sehenswert sind die prächtige Renaissancefassade und der charmante Garten. Von 1616 bis 1796 beherbergte der Palast den Großen Rat, das höchste Gericht der südlichen Niederlande. An der Fassade sind noch heute Margaretes Wappen, das Wappen Karls V. und eine Darstellung der Justitia zu sehen.\n\nMargaretes Leben verlief schon früh turbulent. Nicht weniger als dreimal wurde sie verheiratet beziehungsweise verlobt. Der französische Kronprinz schickte sie im Alter von elf Jahren zurück, nachdem sich für ihn eine günstigere Verbindung ergeben hatte. Der spanische Thronfolger Don Juan starb nur wenige Monate nach der Hochzeit. Philibert von Savoyen, die große Liebe ihres Lebens, verstarb nach drei glücklichen Ehejahren. Die damals vierundzwanzigjährige Margarete trug fortan Witwenkleidung und weigerte sich, erneut zu heiraten.\n\n1507 wurde Margarete zur Statthalterin der Niederlande ernannt und ließ sich in Mechelen nieder. Sie übernahm die Erziehung des späteren Kaisers Karl und seiner Schwestern. Zeitgenossen zufolge führte sie das Land mit Takt und Weitsicht. Einer ihrer größten Erfolge war der Damenfriede von Cambrai im Jahr 1529, den sie nach schwierigen Verhandlungen mit Luise von Savoyen, der Mutter des französischen Königs und Schwester des verstorbenen Philibert, erreichte.\n\nGleichzeitig blühten Kunst und Wissenschaft an Margaretes Hof auf. Bedeutende Künstler und Philosophen hielten sich im Palast auf, und mehrstimmige Musik gehörte zu den großen Leidenschaften der Statthalterin. Ihr originales Graduale wird im Stadtarchiv von Mechelen aufbewahrt und zählt zu den hervorgehobenen Werken des flämischen Kulturerbes.\n\nNach den derzeit auf der Website hinterlegten Angaben ist der Garten des Palastes von Margarete von Österreich an Werktagen von 07:30 bis 16:15 Uhr und samstags von 08:30 bis 15:30 Uhr geöffnet; sonntags bleibt er geschlossen. Für die Sommermonate ist samstags eine Öffnung bis 18:00 Uhr angegeben.'
    },
    'attraction_1769868402831': {
        'title_es': 'GRAN BEGUINAJE',
        'title_de': 'GROSSER BEGINENHOF',
        'description_es': 'Hacia 1560 fue destruido el beguinaje situado fuera de las murallas. Las beguinas volvieron a instalarse dentro de la ciudad, donde fue creciendo el Gran Beguinaje. Compraron edificios existentes y construyeron nuevas viviendas, lo que explica por qué este beguinaje tiene un carácter bastante diferente al de otras ciudades.\n\nPor su carácter típicamente flamenco y su arquitectura singular, el Gran Beguinaje fue declarado Patrimonio Mundial por la UNESCO. Sus pequeñas casas están protegidas. Mientras paseas por sus tranquilas y pintorescas calles, recuerda respetar la privacidad de quienes viven allí.\n\nLos beguinajes eran pequeñas ciudades dentro de la ciudad. Contaban con su propia panadería, cervecería, enfermería, iglesia y terrenos para blanquear tejidos. Surgieron en tiempos de las Cruzadas. Muchos hombres que partieron no regresaron y aumentó el número de viudas, huérfanas y mujeres que no encontraban un marido adecuado. Entrar en un convento era una posibilidad, pero muchos conventos aceptaban principalmente a mujeres aristocráticas o acomodadas.\n\nLas mujeres que, por cualquier motivo, no entraban en un convento comenzaron a vivir juntas y a mantenerse de forma comunitaria. La principal diferencia con los conventos era que las beguinas no pronunciaban votos perpetuos de pobreza, obediencia y castidad. Por tanto, no quedaban ligadas de por vida al beguinaje, aunque muchas permanecían allí hasta el final de sus días. Al principio la Iglesia las trató como herejes, pero fueron siendo aceptadas gradualmente con la condición de llevar una vida piadosa. Así surgieron los beguinajes de Flandes. Al frente se encontraba una Gran Maestra, asistida por otras maestras en la organización y coordinación de la vida cotidiana.\n\nLas beguinas ricas, a menudo de origen aristocrático, construían o compraban su propia casa en el beguinaje. Las menos acomodadas alquilaban una habitación a estas propietarias y colaboraban con las tareas domésticas. Las beguinas sin bienes eran acogidas en pequeños conventos, generalmente fundados por benefactores para asegurar que se rezara por ellos o por familiares fallecidos. Las beguinas que vivían allí debían trabajar para mantenerse. Esta es una de las razones por las que la elaboración de encaje se convirtió en una actividad fundamental a partir del siglo XVII. El beguinaje desempeñó así un papel crucial en la industria del encaje de Malinas.',
        'description_de': 'Um 1560 wurde der Beginenhof außerhalb der Stadtmauern zerstört. Die Beginen ließen sich daraufhin wieder innerhalb der Mauern nieder, wo der Große Beginenhof entstand. Sie kauften bestehende Gebäude und errichteten neue Wohnhäuser. Dadurch unterscheidet sich der Große Beginenhof in seinem Charakter deutlich von Beginenhöfen anderer Städte.\n\nWegen seines typisch flämischen Charakters und seiner besonderen Architektur wurde der Große Beginenhof zum UNESCO-Welterbe erklärt. Die kleinen Häuser stehen unter Denkmalschutz. Wenn Sie durch die ruhigen, malerischen Gassen spazieren, respektieren Sie bitte die Privatsphäre der Bewohner.\n\nBeginenhöfe waren kleine Städte in der Stadt. Sie besaßen eine eigene Bäckerei, Brauerei, Krankenpflege, Kirche und Bleichwiesen. Ihre Entstehung geht auf die Zeit der Kreuzzüge zurück. Viele Männer, die zu einem Kreuzzug aufbrachen, kehrten nicht zurück. Dadurch gab es zahlreiche Witwen, Waisen und Frauen, die keinen passenden Ehemann fanden. Ein Kloster bot eine Möglichkeit, doch viele Klöster nahmen vor allem adelige oder wohlhabende Frauen auf.\n\nFrauen, die aus welchem Grund auch immer nicht in ein Kloster eintraten, lebten gemeinschaftlich zusammen und sorgten gemeinsam für ihren Lebensunterhalt. Der wichtigste Unterschied zum Kloster bestand darin, dass Beginen keine lebenslangen Gelübde von Armut, Gehorsam und Keuschheit ablegten. Sie waren daher nicht für ihr gesamtes Leben an den Beginenhof gebunden, auch wenn viele tatsächlich bis an ihr Lebensende dort wohnten. Anfangs betrachtete die Kirche sie als Ketzerinnen, doch nach und nach wurden sie unter der Voraussetzung eines frommen Lebens akzeptiert. So entstanden die Beginenhöfe in Flandern. Geleitet wurde ein Beginenhof von einer Großmeisterin, die bei Organisation und Koordination des täglichen Lebens von Meisterinnen unterstützt wurde.\n\nWohlhabende, häufig adelige Beginen bauten ein eigenes Haus oder kauften eines im Beginenhof. Weniger vermögende Beginen mieteten bei diesen Eigentümerinnen ein Zimmer und übernahmen Aufgaben im Haushalt. Beginen ohne eigenen Besitz fanden Unterkunft in kleinen Konventen, die meist von Wohltätern gegründet worden waren, damit für sie oder verstorbene Familienmitglieder gebetet wurde. Die dort lebenden Beginen mussten für ihren Lebensunterhalt arbeiten. Das ist einer der Gründe, warum das Spitzenklöppeln im 17. Jahrhundert zu einer der wichtigsten Tätigkeiten wurde. Der Beginenhof spielte deshalb eine entscheidende Rolle in der Mechelner Spitzenindustrie.'
    },
    'attraction_1769868471069': {
        'title_es': 'SENDERO DEL DIJLE',
        'title_de': 'DIJLE-PFAD',
        'description_es': 'A los habitantes de Malinas les gusta disfrutar de su ciudad - y con razón. Pasear junto al agua en pleno centro es una experiencia única y relajante, especialmente cuando recorres el tramo flotante del sendero del Dijle.\n\nEl camino sigue - y en algunos puntos cruza - el río Dijle entre Haverwerf y el Jardín Botánico. Descubre una perspectiva diferente de Malinas y observa la parte trasera de sus antiguas casas. Las numerosas aves acuáticas crean una atmósfera especial y hacen que el paseo también resulte entretenido para los niños.',
        'description_de': 'Die Menschen in Mechelen genießen ihre Stadt gerne - und das aus gutem Grund. Ein Spaziergang am Wasser mitten im Zentrum ist ein besonderes und entspannendes Erlebnis, vor allem auf dem schwimmenden Abschnitt des Dijle-Pfads.\n\nDer Weg führt entlang und teilweise über die Dijle zwischen Haverwerf und Botanischem Garten. Entdecken Sie Mechelen aus einer anderen Perspektive und sehen Sie die Rückseiten der alten Häuser. Die vielen Wasservögel sorgen für eine besondere Atmosphäre und machen den Spaziergang auch für Kinder interessant.'
    }
}

for item_id, values in translations.items():
    patch(item_id, values)

print(f'Applied Spanish and German translations to {len(translations)} attraction records.')
